[workspace]
resolver = "2"
members = ["crates/*"]
default-members = ["crates/*"]

[workspace.package]
edition = "2024"
authors = ["Ali Samji <aisamji@users.noreply.github.com>"]
license-file = "LICENSE"
repository = "https://github.com/aisamji/kube-observe"

[workspace.dependencies]