[package]
name = "kube-observe"
description = "Helpers for managing conditions and events in kubernetes."
version = "0.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
